version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    restart: always
    env_file:
      - .env
    environment:
       - AIRFLOW__CORE__EXECUTOR=${EXECUTOR}
       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${SQL_ALCHEMY}
       - AIRFLOW__CORE__FERNET_KEY=
       - AIRFLOW__CORE__LOAD_EXAMPLES=False
       - DB_USER=${DB_USER}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_HOST=${DB_HOST}
       - DB_PORT=${DB_PORT}
       - DB_NAME=${DB_NAME}
       - _AIRFLOW_WWW_USER_CREATE=true
       - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_USER}
       - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_PASSWORD}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: webserver

  airflow_scheduler:
    build: ./airflow
    restart: always
    depends_on:
      - db
      - airflow
    environment:
      - EXECUTOR=CeleryExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./airflow/dbt_project:/opt/airflow/dbt_project
    command: scheduler

volumes:
  pgdata: