version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    restart: always
    env_file:
      - .env
    # environment:
    #    - EXECUTOR=LocalExecutor
    #    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgresql:admin@db:5432/covid19_project
    #    - AIRFLOW__CORE__FERNET_KEY=
    #    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    #    - DB_USER=postgresql
    #    - DB_PASSWORD=admin
    #    - DB_HOST=db
    #    - DB_PORT=5432
    #    - DB_NAME=covid19_project
    #    - _AIRFLOW_WWW_USER_CREATE=true
    #    - _AIRFLOW_WWW_USER_USERNAME=airflow
    #    - _AIRFLOW_WWW_USER_PASSWORD=airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: webserver

  airflow_scheduler:
    build: ./airflow
    restart: always
    depends_on:
      - db
      - airflow
    environment:
      - EXECUTOR=CeleryExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    command: scheduler

volumes:
  pgdata: