my_covid19_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgresql
      password: admin
      port: 5432
      dbname: covid19_project
      schema: public
